services:

  # -------------------------------
  # Transaction Validator Blue
  # -------------------------------
  transaction-validator-blue:
    build:
      context: .
    image: transaction-validator-blue:latest
    container_name: transaction-validator-blue
    command: npm start
    ports:
      - "3001:3000"
    volumes:
      - ./logs:/app/logs
    environment:
      NODE_ENV: production
      PORT: 3000
    depends_on:
      - prometheus
      - loki
      - jaeger
      - promtail

  # -------------------------------
  # Transaction Validator Green
  # -------------------------------
  transaction-validator-green:
    build:
      context: .
    image: transaction-validator-green:latest
    container_name: transaction-validator-green
    command: npm start
    ports:
      - "3002:3000"
    volumes:
      - ./logs:/app/logs
    environment:
      NODE_ENV: production
      PORT: 3000
    depends_on:
      - prometheus
      - loki
      - jaeger
      - promtail

  # -------------------------------
  # Prometheus (MÃ©tricas)
  # -------------------------------
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # -------------------------------
  # Loki (Logs)
  # -------------------------------
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"

  # -------------------------------
  # Promtail (Logs -> Loki)
  # -------------------------------
  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - ./logs:/app/logs
      - ./monitoring/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  # -------------------------------
  # Grafana
  # -------------------------------
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./monitoring/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
      - loki

  # -------------------------------
  # Jaeger
  # -------------------------------
  jaeger:
    image: jaegertracing/all-in-one:1.41
    container_name: jaeger
    ports:
      - "16686:16686"
      - "14268:14268"

volumes:
  grafana-storage:
