apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe -f docker-compose.yml convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: jaeger
  name: jaeger
spec:
  type: NodePort
  ports:
    - name: "16686"
      port: 16686
      targetPort: 16686
      nodePort: 30086
    - name: "14268"
      port: 14268
      targetPort: 14268
      nodePort: 30068

  selector:
    io.kompose.service: jaeger
