apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe -f docker-compose.yml convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: loki
  name: loki
spec:
  type: NodePort
  ports:
    - name: "3100"
      port: 3100
      targetPort: 3100
      nodePort: 30100
  selector:
    io.kompose.service: loki
