apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe -f docker-compose.yml convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: promtail
  name: promtail
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: promtail
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe -f docker-compose.yml convert
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: promtail
    spec:
      containers:
        - args:
            - -config.file=/etc/promtail/config.yml
          image: grafana/promtail:2.9.0
          name: promtail
          volumeMounts:
            - mountPath: /var/log/app
              name: promtail-cm0
            - mountPath: /etc/promtail/config.yml
              name: promtail-cm1
              subPath: config.yml
      restartPolicy: Always
      volumes:
        - configMap:
            name: promtail-cm0
          name: promtail-cm0
        - configMap:
            items:
              - key: promtail-config.yml
                path: config.yml
            name: promtail-cm1
          name: promtail-cm1
