apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-validator-blue
  labels:
    app: transaction-validator
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-validator
      version: blue
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: transaction-validator
        version: blue
    spec:
      containers:
      - name: transaction-validator
        image: transaction-validator-blue:latest
        args: ["npm","start"]
        imagePullPolicy: Never

        env:
          - name: NODE_ENV
            value: production
          - name: PORT
            value: "3000"
        ports:
          - containerPort: 3000
        volumeMounts:
          - mountPath: /app/logs
            name: transaction-validator-blue-logs
      restartPolicy: Always
      volumes:
        - name: transaction-validator-blue-logs
          persistentVolumeClaim:
            claimName: transaction-validator-blue-logs-pvc
          
