apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe -f docker-compose.yml convert
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: transaction-validator-green
  name: transaction-validator-green
spec:
  type: NodePort
  ports:
    - name: "3002"
      port: 3002
      targetPort: 3000
      nodePort: 30002
  selector:
    io.kompose.service: transaction-validator-green
